"""Egypt-specific city profiles, service copy, and contact constants."""

# Egypt desk used on rukn-eltatawer.com/eg FAQ and sister homepages (01556644443).
PHONE_LOCAL = "01556644443"
PHONE_INTL = "201556644443"
PHONE_TEL = f"+{PHONE_INTL}"
WHATSAPP_INTL = PHONE_INTL
WHATSAPP_URL = (
    f"https://wa.me/{WHATSAPP_INTL}"
    "?text=%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%D9%8B%20%D8%B1%D9%83%D9%86%20%D8%A7%D9%84%D8%AA%D8%B7%D9%88%D8%B1%20%D9%85%D8%B5%D8%B1"
)
SITE_HOME = "https://rukn-eltatawer.com/eg"
BRAND_AR = "ركن التطور"
BRAND_EN = "Rukn El Tatawer"
UPDATED_AR = "سبتمبر 2026"
UPDATED_EN = "September 2026"


def post_url(slug: str) -> str:
    return f"{SITE_HOME}/{slug.strip('/')}/"


def page_url(slug: str) -> str:
    return f"{SITE_HOME}/{slug.strip('/')}/"

# city -> profile used to kill copy-paste doorway text
CITIES = {
    "التجمع الخامس": {
        "en": "Fifth Settlement",
        "slug": "fifth-settlement",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "premium",
        "climate_ar": "مناخ صحراوي حار صيفًا مع رياح خماسين وأتربة، ما يضغط على الدهانات الخارجية والعزل والتكييف.",
        "climate_en": "Hot desert summers and khamsin dust, which stress exterior paint, insulation, and air-conditioning.",
        "stock_ar": "كمبوندات حديثة على الطوب الأحمر وشقق تسليم شركة تحتاج تشطيبًا كاملًا، مع لوائح اتحاد ملاك وتصاريح دخول للمقاولين.",
        "stock_en": "New compounds delivered as brick-and-shell units, plus owner-association rules and contractor gate permits.",
        "places_ar": "ميفيدا، هايد بارك، قطامية هايتس، الباتيو، ماونتن فيو، تاج سيتي، سوديك إيست، جاليريا ريزيدنس، كايرو فستيفال سيتي",
        "places_en": "Mivida, Hyde Park, Katameya Heights, The Patio, Mountain View, Taj City, SODIC East, Galleria, Cairo Festival City",
        "access_ar": "محور محمد بن زايد والطريق الدائري الأوسط، مع بوابات أمن تؤخر التوريد إن لم يُنسَّق مسبقًا.",
        "access_en": "Mohamed Bin Zayed Axis and the Middle Ring Road; security gates delay deliveries without prior clearance.",
        "price_note_ar": "تكلفة الخامات والعمالة في التجمع أقرب لشرائح القاهرة الجديدة الفاخرة بالجنيه المصري، وتختلف حسب الكمبوند ولوائح التشطيب.",
        "price_note_en": "Materials and labor track New Cairo premium bands in EGP and vary by compound finishing rules.",
    },
    "الشيخ زايد": {
        "en": "Sheikh Zayed",
        "slug": "sheikh-zayed",
        "gov_ar": "الجيزة",
        "gov_en": "Giza",
        "tier": "premium",
        "climate_ar": "حرارة مرتفعة ورطوبة نسبية أقل من الإسكندرية، مع أسطح واسعة تحتاج عزلًا حراريًا ومائيًا.",
        "climate_en": "High heat and large villa roofs that need thermal and waterproof insulation.",
        "stock_ar": "فلل تاون هاوس وكمبوندات غرب القاهرة (أرابella، الياسمين، بيفرلي هيلز، أليجاز، كونتيننتال).",
        "stock_en": "Townhouses and west-Cairo compounds such as Arabella, Yasmeen, Beverly Hills, Allegria and Continental.",
        "places_ar": "بيفرلي هيلز، أليجاز، الياسمين، أرابيلا، كونتيننتال ريزيدنس",
        "places_en": "Beverly Hills, Allegria, Yasmeen, Arabella, Continental Residence",
        "access_ar": "محور 26 يوليو ووصلة دهشور؛ مواعيد التوريد داخل الكمبوندات مقيدة.",
        "access_en": "26th of July Corridor and Dahshur link; compound delivery windows are restricted.",
        "price_note_ar": "أسعار التشطيبات في الشيخ زايد تتأثر بخامات الواجهات ومساحات الحدائق بالجنيه المصري.",
        "price_note_en": "Finishing prices in Sheikh Zayed follow facade materials and garden areas, quoted in EGP.",
    },
    "6 أكتوبر": {
        "en": "6th of October",
        "slug": "6th-of-october",
        "gov_ar": "الجيزة",
        "gov_en": "Giza",
        "tier": "mid",
        "climate_ar": "صيف حار وأتربة طريق الواحات، ما يظهر في فلاتر التكييف ودهان الواجهات.",
        "climate_en": "Hot summers and Wahat-road dust that clog AC filters and weather exterior paint.",
        "stock_ar": "مزيج من عمارات سكنية وكمبوندات (أشجار، جهينة، دريم لاند) ومناطق صناعية مجاورة.",
        "stock_en": "Apartment blocks, compounds such as Ashgar, Juhayna and Dreamland, plus nearby industrial zones.",
        "places_ar": "أشجار، جهينة، دريم لاند، الحي المتميز، غرب سوميد",
        "places_en": "Ashgar, Juhayna, Dreamland, Distinctive District, West Somid",
        "access_ar": "طريق الواحات ومحور 26 يوليو؛ الازدحام صباحًا يؤخر فرق العمل.",
        "access_en": "Wahat Road and 26th of July Corridor; morning congestion delays crews.",
        "price_note_ar": "شريحة سعرية أوسع من الشيخ زايد، بالجنيه، حسب الحي ونوع العقار.",
        "price_note_en": "Wider EGP price band than Sheikh Zayed, depending on district and property type.",
    },
    "العاصمة الإدارية الجديدة": {
        "en": "New Administrative Capital",
        "slug": "new-capital",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "premium",
        "climate_ar": "هضبة شرق القاهرة أشد جفافًا وحرارة؛ العزل الحراري للأسطح والزجاج ضرورة.",
        "climate_en": "The eastern plateau is hotter and drier; roof and glass thermal insulation is essential.",
        "stock_ar": "أبراج سكنية وكمبوندات R7 وR8 وداون تاون وحي الوزارات بمواصفات تسليم حديثة ولوائح صارمة.",
        "stock_en": "Towers and R7/R8, Downtown and Ministries-district compounds with strict handover specs.",
        "places_ar": "R7، R8، الداون تاون، حي السفارات، البيت الأخضر",
        "places_en": "R7, R8, Downtown, Embassy District, Green River",
        "access_ar": "الفنطاس والطريق الإقليمي؛ يحتاج التنسيق تصاريح دخول للمواقع الجديدة.",
        "access_en": "Fintass and the Regional Ring Road; new sites require entry permits.",
        "price_note_ar": "خامات المواصفات الحكومية والكمبوندات الجديدة ترفع متوسط التكلفة بالجنيه.",
        "price_note_en": "Government-spec and new-compound materials raise the average EGP budget.",
    },
    "مدينتي": {
        "en": "Madinaty",
        "slug": "madinaty",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "premium",
        "climate_ar": "اتساع المساحات المكشوفة يزيد الغبار على الواجهات والنوافذ.",
        "climate_en": "Wide open spaces increase dust on facades and windows.",
        "stock_ar": "مدينة متكاملة ببنايات متكررة وحدائق مركزية ولوائح تشطيب ألوان محددة من المطور.",
        "stock_en": "A master-planned city with repeating blocks, central parks, and developer color rules.",
        "places_ar": "B11، B12، المنطقة السياحية، الجولف، البيوت",
        "places_en": "B11, B12, Tourism Area, Golf, El-Beyoot",
        "access_ar": "طريق السويس وبوابات مدينتي؛ التوريد بمواعيد محددة.",
        "access_en": "Suez Road and Madinaty gates with timed deliveries.",
        "price_note_ar": "التشطيب محكوم بدليل المطور، والسعر بالجنيه حسب المساحة ونوع التشطيب.",
        "price_note_en": "Finishing follows the developer handbook; EGP pricing follows area and finish grade.",
    },
    "الزمالك": {
        "en": "Zamalek",
        "slug": "zamalek",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "heritage",
        "climate_ar": "رطوبة النيل تسرّع تلف الدهانات الخشبية والحديد المشغول.",
        "climate_en": "Nile humidity speeds decay of wood finishes and wrought iron.",
        "stock_ar": "عمارات تراثية وشقق عالية الأسقف تحتاج ترميمًا أدق من التشطيب الحديث.",
        "stock_en": "Heritage buildings and high-ceiling flats that need careful restoration, not only new finishes.",
        "places_ar": "شارع 26 يوليو، أبو الفدا، الجزيرة، محيط الأوبرا",
        "places_en": "26th of July Street, Abu El Feda, Gezira, Opera surroundings",
        "access_ar": "شوارع ضيقة ومواقف محدودة؛ التوريد غالبًا يدويًا أو بسيارات صغيرة.",
        "access_en": "Narrow streets and scarce parking; deliveries are often by hand or small vans.",
        "price_note_ar": "أعمال الترميم والخشب ترتفع تكلفتها عن التشطيب الجديد بالجنيه.",
        "price_note_en": "Restoration and carpentry cost more in EGP than a new-build finish.",
    },
    "مدينة نصر": {
        "en": "Nasr City",
        "slug": "nasr-city",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "mid",
        "climate_ar": "كثافة مرورية وغبار حضري يؤثران على الواجهات والنوافذ الألوميتال.",
        "climate_en": "Traffic density and urban dust affect facades and aluminium windows.",
        "stock_ar": "عمارات السبعينيات والثمانينيات إلى أحياء أحدث مثل السفارات والحي الثامن.",
        "stock_en": "1970s–80s blocks plus newer zones such as the Embassies area and 8th District.",
        "places_ar": "الحي الثامن، السفارات، زهراء مدينة نصر، عباس العقاد",
        "places_en": "8th District, Embassies, Zahraa Nasr City, Abbas El Akkad",
        "access_ar": "الأوتوستراد وصلاح سالم؛ مواعيد العمل داخل العمارات تحتاج إذن السكان.",
        "access_en": "Autostrad and Salah Salem; in-building work needs resident permission.",
        "price_note_ar": "إعادة التشطيب أكثر شيوعًا من التشطيب من الصفر، والتسعير بالجنيه حسب حالة العقار.",
        "price_note_en": "Refurbishment is more common than shell-and-core; EGP quotes follow building condition.",
    },
    "المقطم": {
        "en": "Mokattam",
        "slug": "mokattam",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "mid",
        "climate_ar": "ارتفاع الهضبة ورياح أقوى تستدعي تثبيتًا أقوى للواجهات والخزانات.",
        "climate_en": "Plateau winds require stronger facade fixing and tank anchoring.",
        "stock_ar": "فلل على الهضبة وعمارات في الهضبة الوسطى والبيضاء مع فروق منسوب كبيرة.",
        "stock_en": "Plateau villas and mid/white-plateau blocks with large elevation changes.",
        "places_ar": "الهضبة العليا، الهضبة الوسطى، المقطم الجديدة",
        "places_en": "Upper Plateau, Middle Plateau, New Mokattam",
        "access_ar": "صعود الهضبة يقيّد سيارات النقل الثقيل في بعض الشوارع.",
        "access_en": "The climb limits heavy trucks on some streets.",
        "price_note_ar": "أعمال العزل والواجهات أعلى تكلفة بسبب الرياح والارتفاع، بالجنيه المصري.",
        "price_note_en": "Insulation and facades cost more in EGP because of wind and elevation.",
    },
    "العبور": {
        "en": "Obour",
        "slug": "obour",
        "gov_ar": "القليوبية",
        "gov_en": "Qalyubia",
        "tier": "mid",
        "climate_ar": "مدينة صناعية سكنية؛ الغبار الصناعي والرطوبة الموسمية يؤثران على الدهانات.",
        "climate_en": "Industrial-residential city; factory dust and seasonal humidity affect paint.",
        "stock_ar": "أحياء سكنية حديثة وجولف العبور ومناطق مصانع مجاورة.",
        "stock_en": "Newer residential districts, Obour Golf, and nearby factories.",
        "places_ar": "الجولف، الحي الأول، الحي السابع، العبور الجديدة",
        "places_en": "Golf, 1st District, 7th District, New Obour",
        "access_ar": "الطريق الدائري وبلبيس؛ التوريد أسهل من وسط القاهرة.",
        "access_en": "Ring Road and Belbeis Road; deliveries are easier than central Cairo.",
        "price_note_ar": "تكلفة العمالة والخامات بالجنيه أقل نسبيًا من التجمع في معظم البنود.",
        "price_note_en": "EGP labor and materials are usually lower than Fifth Settlement.",
    },
    "بدر": {
        "en": "Badr City",
        "slug": "badr",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "value",
        "climate_ar": "أطراف صحراوية حارة؛ العزل المائي للأسطح مهم بعد الأمطار النادرة لكنها الغزيرة.",
        "climate_en": "Hot desert edge; roof waterproofing matters after rare but heavy rain.",
        "stock_ar": "إسكان متوسط وجامعات ومصانع، مع وحدات جديدة تحتاج تشطيبًا اقتصاديًا متينًا.",
        "stock_en": "Mid-income housing, universities and factories, plus new units needing durable economy finishes.",
        "places_ar": "حي الجامعة، المنطقة الصناعية، بدر الجديدة",
        "places_en": "University district, industrial zone, New Badr",
        "access_ar": "طريق السويس؛ مسافات التوريد أطول من القاهرة الجديدة.",
        "access_en": "Suez Road; haul distances are longer than New Cairo.",
        "price_note_ar": "ميزانيات تشطيب اقتصادية بالجنيه مع التركيز على المتانة لا الخامات الفاخرة.",
        "price_note_en": "Economy EGP budgets that prioritize durability over luxury materials.",
    },
    "أكتوبر الجديدة": {
        "en": "New October",
        "slug": "new-october",
        "gov_ar": "الجيزة",
        "gov_en": "Giza",
        "tier": "mid",
        "climate_ar": "امتداد صحراوي لأكتوبر؛ الحرارة والغبار أعلى من الأحياء القديمة.",
        "climate_en": "Desert extension of October City with more heat and dust than older districts.",
        "stock_ar": "كمبوندات جديدة وإسكان متوسط على مراحل تسليم مختلفة.",
        "stock_en": "New compounds and mid-income housing in staggered handover phases.",
        "places_ar": "حدائق أكتوبر المجاورة، أحياء التوسعات الغربية",
        "places_en": "Hadayek October nearby and western expansion districts",
        "access_ar": "طريق الواحات وتوسعات غرب أكتوبر.",
        "access_en": "Wahat Road and west-October expansions.",
        "price_note_ar": "أسعار بالجنيه بين 6 أكتوبر والشيخ زايد حسب الكمبوند.",
        "price_note_en": "EGP pricing sits between 6th of October and Sheikh Zayed by compound.",
    },
    "حدائق أكتوبر": {
        "en": "Hadayek October",
        "slug": "hadayek-october",
        "gov_ar": "الجيزة",
        "gov_en": "Giza",
        "tier": "mid",
        "climate_ar": "قرب المساحات الخضراء يرفع الرطوبة الليلية على الجبس والخشب.",
        "climate_en": "Greener pockets raise night humidity on gypsum and wood.",
        "stock_ar": "فيلات وعمارات حديثة بكثافة أقل من 6 أكتوبر القديمة.",
        "stock_en": "Newer villas and blocks at lower density than old October.",
        "places_ar": "أحياء الحدائق، محاور الخدمة المحلية",
        "places_en": "Garden districts and local service corridors",
        "access_ar": "مداخل أكتوبر الغربية؛ التنسيق مع الأمن المحلي مطلوب في بعض التجمعات.",
        "access_en": "West October entries; some clusters need local security clearance.",
        "price_note_ar": "تسعير بالجنيه أقرب للفيلات متوسطة المساحة.",
        "price_note_en": "EGP quotes closer to mid-size villa work.",
    },
    "المنصورة": {
        "en": "Mansoura",
        "slug": "mansoura",
        "gov_ar": "الدقهلية",
        "gov_en": "Dakahlia",
        "tier": "delta",
        "climate_ar": "رطوبة دلتا عالية صيفًا؛ التسريبات والعفن أكثر شيوعًا من القاهرة الصحراوية.",
        "climate_en": "High Delta humidity; leaks and mold are more common than in desert Cairo.",
        "stock_ar": "عمارات على النيل وبيوت قديمة في وسط المدينة تحتاج سباكة وكهرباء محدثة.",
        "stock_en": "Nile-front blocks and older downtown houses that need updated plumbing and electrics.",
        "places_ar": "طلخا، حي الجامعة، شارع الجمهورية، المشاية",
        "places_en": "Talkha-side, University area, Gomhoreya Street, Mashaya",
        "access_ar": "كوبري الجامعة والزراعة؛ الشوارع الداخلية ضيقة وقت الذروة.",
        "access_en": "University and Agriculture bridges; inner streets jam at peak hours.",
        "price_note_ar": "أجرة الفنيين بالجنيه أقل من القاهرة الجديدة، والخامات تتأثر بنقل الجملة من القاهرة.",
        "price_note_en": "EGP trades rates are below New Cairo; materials follow wholesale freight from Cairo.",
    },
    "المنصورة الجديدة": {
        "en": "New Mansoura",
        "slug": "new-mansoura",
        "gov_ar": "الدقهلية",
        "gov_en": "Dakahlia",
        "tier": "coastal",
        "climate_ar": "مدينة ساحلية على المتوسط؛ الرطوبة والملوحة تسرّع تآكل المعادن والدهان.",
        "climate_en": "Mediterranean new city; salt and humidity corrode metal and paint faster.",
        "stock_ar": "أبراج ساحلية وشقق جديدة تحتاج خامات مقاومة للملوحة من اليوم الأول.",
        "stock_en": "Coastal towers and new flats that need salt-resistant materials from day one.",
        "places_ar": "الأحياء السكنية الأولى، الواجهة البحرية",
        "places_en": "First residential districts and the seafront",
        "access_ar": "طريق جمصة والمنصورة الجديدة؛ التوريد حسب مراحل التسليم.",
        "access_en": "Gamasa–New Mansoura road; deliveries follow handover phases.",
        "price_note_ar": "خامات مقاومة للملوحة ترفع بند التشطيب بالجنيه عن المنصورة الداخلية.",
        "price_note_en": "Salt-resistant materials raise the EGP finish line above inland Mansoura.",
    },
    "دمياط الجديدة": {
        "en": "New Damietta",
        "slug": "new-damietta",
        "gov_ar": "دمياط",
        "gov_en": "Damietta",
        "tier": "coastal",
        "climate_ar": "رطوبة وملوحة أعلى؛ الأخشاب غير المعالجة تتمدد وتتفكك أسرع.",
        "climate_en": "Higher humidity and salt; untreated wood swells and fails faster.",
        "stock_ar": "مدينة مخططة بمصايف وشقق سكنية قرب الأثاث الدمياتي.",
        "stock_en": "A planned city of summer homes and apartments near Damietta furniture trade.",
        "places_ar": "الحي المميز، الشريط الساحلي، المنطقة المركزية",
        "places_en": "Distinctive district, coastal strip, central zone",
        "access_ar": "طريق دمياط بورسعيد؛ مواسم الصيف تزحم التوريد.",
        "access_en": "Damietta–Port Said road; summer season crowds deliveries.",
        "price_note_ar": "توفر الأثاث المحلي يخفض بعض بنود النجارة بالجنيه ويرفع بنود العزل الساحلي.",
        "price_note_en": "Local furniture lowers some carpentry EGP lines and raises coastal insulation lines.",
    },
    "سموحة": {
        "en": "Smouha",
        "slug": "smouha",
        "gov_ar": "الإسكندرية",
        "gov_en": "Alexandria",
        "tier": "coastal",
        "climate_ar": "رطوبة إسكندرانية دائمة؛ الدهانات الداخلية تحتاج مقاومة للعفن.",
        "climate_en": "Persistent Alexandrian humidity; interior paints need mold resistance.",
        "stock_ar": "كمبوندات وعمارات حديثة حول النادي ومنطقة فيكتوريا المجاورة.",
        "stock_en": "Newer compounds and blocks around the club and nearby Victoria.",
        "places_ar": "سموحة الجديدة، النادي، محيط جامعة الإسكندرية",
        "places_en": "New Smouha, the club, Alexandria University surroundings",
        "access_ar": "محور المحمودية وبوابات داخلية في بعض العمارات.",
        "access_en": "Mahmoudia axis and internal building gates.",
        "price_note_ar": "تسعير بالجنيه أقرب لأحياء الإسكندرية الراقية لا لقرى الساحل الموسمية.",
        "price_note_en": "EGP pricing tracks upscale Alexandria, not seasonal North Coast villages.",
    },
    "برج العرب الجديدة": {
        "en": "New Borg El Arab",
        "slug": "new-borg-el-arab",
        "gov_ar": "الإسكندرية",
        "gov_en": "Alexandria",
        "tier": "coastal",
        "climate_ar": "قرب المتوسط مع رياح وأتربة طريق مطروح؛ الواجهات تتسخ أسرع.",
        "climate_en": "Mediterranean wind plus Matrouh-road dust dirties facades faster.",
        "stock_ar": "مدينة جديدة وجامعات ومناطق سكنية واسعة تحتاج تشطيبًا من الصفر.",
        "stock_en": "A new city with universities and large housing tracts that need shell-and-core finishing.",
        "places_ar": "الأحياء السكنية، المنطقة الصناعية، محيط الجامعة",
        "places_en": "Residential districts, industrial zone, university belt",
        "access_ar": "طريق الإسكندرية مطروح؛ التوريد من الإسكندرية يستغرق وقتًا أطول.",
        "access_en": "Alexandria–Matrouh road; freight from Alexandria takes longer.",
        "price_note_ar": "تكلفة النقل بالجنيه أوضح هنا من أحياء الإسكندرية الداخلية.",
        "price_note_en": "EGP haulage is a clearer line item than in inner Alexandria.",
    },
    "طنطا": {
        "en": "Tanta",
        "slug": "tanta",
        "gov_ar": "الغربية",
        "gov_en": "Gharbia",
        "tier": "delta",
        "climate_ar": "قلب الدلتا رطب؛ أعمال السباكة والعزل أهم من القاهرة الجافة.",
        "climate_en": "Humid central Delta; plumbing and insulation matter more than in dry Cairo.",
        "stock_ar": "وسط تجاري كثيف وبيوت قديمة وأحياء جديدة على أطراف المدينة.",
        "stock_en": "A dense commercial core, older houses, and newer edge districts.",
        "places_ar": "السيون، الحي الأول، منطقة الاستاد، طريق المحلة",
        "places_en": "Saioun, 1st District, Stadium area, Mahalla road",
        "access_ar": "شبكة السكة الحديد والطرق الزراعية تزحم التوريد وسط البلد.",
        "access_en": "Rail and farm roads congest downtown deliveries.",
        "price_note_ar": "أجور حرفيين بالجنيه تنافسية، والخامات تعتمد على تجار طنطا والمحلة.",
        "price_note_en": "Competitive EGP trade rates; materials follow Tanta and Mahalla merchants.",
    },
    "الزقازيق": {
        "en": "Zagazig",
        "slug": "zagazig",
        "gov_ar": "الشرقية",
        "gov_en": "Sharqia",
        "tier": "delta",
        "climate_ar": "رطوبة زراعية؛ البيارات والتمديدات القديمة شائعة في البيوت.",
        "climate_en": "Agricultural humidity; old cesspits and wiring are common.",
        "stock_ar": "منازل أسرية وعمارات طلابية حول الجامعة.",
        "stock_en": "Family houses and student blocks around the university.",
        "places_ar": "حي الجامعة، المنيرة، القومية",
        "places_en": "University district, Munira, Qawmia",
        "access_ar": "طرق الشرقية الزراعية؛ سيارات النقل الصغيرة أنسب للحواري.",
        "access_en": "Sharqia farm roads; small vans fit alleyways better.",
        "price_note_ar": "تسعير بالجنيه يناسب إعادة التشطيب الجزئي أكثر من الكمبوندات.",
        "price_note_en": "EGP pricing suits partial refurbishment more than compounds.",
    },
    "دمياط": {
        "en": "Damietta",
        "slug": "damietta",
        "gov_ar": "دمياط",
        "gov_en": "Damietta",
        "tier": "coastal",
        "climate_ar": "مدينة أثاث ورطوبة نيلية-ساحلية؛ النجارة محلية قوية والعزل ضروري.",
        "climate_en": "Furniture city with Nile-coastal humidity; local carpentry is strong and insulation is essential.",
        "stock_ar": "بيوت ورش وعمارات قديمة مع نشاط أثاث كثيف.",
        "stock_en": "Workshop houses and older blocks tied to the furniture trade.",
        "places_ar": "رأس البر القريبة، وسط دمياط، المنطقة الصناعية",
        "places_en": "Nearby Ras El Bar, downtown Damietta, industrial zone",
        "access_ar": "كوبري دمياط والطرق الساحلية.",
        "access_en": "Damietta bridge and coastal roads.",
        "price_note_ar": "بنود النجارة بالجنيه أقل غالبًا، وبنود العزل والرطوبة أعلى.",
        "price_note_en": "Carpentry EGP lines are often lower; moisture-proofing lines are higher.",
    },
    "كفر الشيخ": {
        "en": "Kafr El Sheikh",
        "slug": "kafr-el-sheikh",
        "gov_ar": "كفر الشيخ",
        "gov_en": "Kafr El Sheikh",
        "tier": "delta",
        "climate_ar": "أراضٍ منخفضة ورطوبة؛ تسريب المياه الأرضية وارد في الدور الأرضي.",
        "climate_en": "Low land and humidity; ground-floor seepage is common.",
        "stock_ar": "مساكن أسرية ومبانٍ حكومية وأحياء جديدة محدودة.",
        "stock_en": "Family homes, government buildings, and limited new districts.",
        "places_ar": "حي الجامعة، سخا، دسوق القريبة",
        "places_en": "University district, Sakha, nearby Desouk",
        "access_ar": "طرق الدلتا؛ جدولة التوريد أهم من القاهرة.",
        "access_en": "Delta roads; scheduling freight matters more than in Cairo.",
        "price_note_ar": "ميزانيات بالجنيه تميل للأعمال العملية والصيانة قبل الديكور الفاخر.",
        "price_note_en": "EGP budgets favor practical repairs over luxury décor.",
    },
    "بنها": {
        "en": "Banha",
        "slug": "banha",
        "gov_ar": "القليوبية",
        "gov_en": "Qalyubia",
        "tier": "delta",
        "climate_ar": "قرب القاهرة مع رطوبة زراعية؛ إعادة تشطيب العمارات القديمة شائع.",
        "climate_en": "Near Cairo with farm humidity; refurbishing older blocks is common.",
        "stock_ar": "عمارات سكنية وبيوت على النيل وأحياء جامعية.",
        "stock_en": "Apartment blocks, Nile houses, and university districts.",
        "places_ar": "حي الجامعة، المنشية، كورنيش بنها",
        "places_en": "University district, Mansheya, Banha corniche",
        "access_ar": "الطريق الزراعي وبنها الزقازيق؛ قرب القاهرة يسهّل توريد الخامات.",
        "access_en": "Agricultural Road and Banha–Zagazig; Cairo proximity eases materials.",
        "price_note_ar": "أسعار بالجنيه بين القاهرة والدلتا.",
        "price_note_en": "EGP rates sit between Cairo and the wider Delta.",
    },
    "المحلة الكبرى": {
        "en": "El Mahalla El Kubra",
        "slug": "mahalla",
        "gov_ar": "الغربية",
        "gov_en": "Gharbia",
        "tier": "delta",
        "climate_ar": "مدينة صناعية نسيجية؛ الغبار الناعم والرطوبة يؤثران على الدهانات.",
        "climate_en": "Textile-industrial city; fine dust and humidity affect paint.",
        "stock_ar": "مساكن عمالية وعمارات قديمة وأحياء أحدث على الأطراف.",
        "stock_en": "Worker housing, older blocks, and newer edge districts.",
        "places_ar": "المنطقة الصناعية، حي أول، حي ثان",
        "places_en": "Industrial zone, First District, Second District",
        "access_ar": "طرق الغربية؛ الازدحام الصناعي صباحًا.",
        "access_en": "Gharbia roads; industrial morning congestion.",
        "price_note_ar": "تسعير بالجنيه عملي يناسب الصيانة المتكررة.",
        "price_note_en": "Practical EGP pricing suited to frequent maintenance.",
    },
    "الإسماعيلية": {
        "en": "Ismailia",
        "slug": "ismailia",
        "gov_ar": "الإسماعيلية",
        "gov_en": "Ismailia",
        "tier": "canal",
        "climate_ar": "رطوبة قناة السويس وملوحة؛ الحديد والألوميتال يحتاجان حماية.",
        "climate_en": "Suez Canal humidity and salt; steel and aluminium need protection.",
        "stock_ar": "بيوت حدائق وعمارات قديمة ومناطق جديدة على التوسعات.",
        "stock_en": "Garden houses, older blocks, and expansion districts.",
        "places_ar": "الشيخ زايد الإسماعيلية، حي الجمرك، التمساح",
        "places_en": "Ismailia Sheikh Zayed, Customs district, Timsah",
        "access_ar": "طريق القاهرة الإسماعيلية الصحراوي.",
        "access_en": "Cairo–Ismailia desert road.",
        "price_note_ar": "نقل الخامات من القاهرة بند واضح بالجنيه.",
        "price_note_en": "Cairo freight is a visible EGP line.",
    },
    "بورسعيد": {
        "en": "Port Said",
        "slug": "port-said",
        "gov_ar": "بورسعيد",
        "gov_en": "Port Said",
        "tier": "coastal",
        "climate_ar": "ملوحة بحرية عالية؛ أي تشطيب بدون حماية معادن يتآكل سريعًا.",
        "climate_en": "High marine salt; unprotected metal finishes fail quickly.",
        "stock_ar": "عمارات قديمة على الكورنيش وإسكان أحدث في الجنوب والغرب.",
        "stock_en": "Older corniche blocks and newer south/west housing.",
        "places_ar": "حي الشرق، حي المناخ، بورفؤاد",
        "places_en": "Sharq, Makh, Port Fuad",
        "access_ar": "الكوبري العائم والأنفاق؛ التوريد يتأثر بحركة الميناء.",
        "access_en": "Floating bridge and tunnels; port traffic affects deliveries.",
        "price_note_ar": "خامات مقاومة للملوحة ترفع التكلفة بالجنيه عن مدن الدلتا الداخلية.",
        "price_note_en": "Salt-proof materials raise EGP cost above inland Delta cities.",
    },
    "السويس": {
        "en": "Suez",
        "slug": "suez",
        "gov_ar": "السويس",
        "gov_en": "Suez",
        "tier": "canal",
        "climate_ar": "حرارة وملوحة خليج السويس؛ العزل الحراري والمائي أولوية.",
        "climate_en": "Heat and Suez-gulf salt; thermal and waterproof insulation come first.",
        "stock_ar": "مساكن عمالية ومناطق جديدة بعتاقة والأربعين.",
        "stock_en": "Worker housing and newer Ataqa and Arbaeen districts.",
        "places_ar": "الأربعين، عتاقة، حي السويس",
        "places_en": "Arbaeen, Ataqa, Suez district",
        "access_ar": "طريق السويس والعين السخنة.",
        "access_en": "Suez and Ain Sokhna roads.",
        "price_note_ar": "التسعير بالجنيه يراعي نقل الخامات من القاهرة والصعيد أحيانًا.",
        "price_note_en": "EGP quotes allow for freight from Cairo and sometimes Upper Egypt.",
    },
    "بني سويف": {
        "en": "Beni Suef",
        "slug": "beni-suef",
        "gov_ar": "بني سويف",
        "gov_en": "Beni Suef",
        "tier": "upper",
        "climate_ar": "صعيد أقرب للقاهرة؛ حرارة عالية وغبار، والرطوبة أقل من الدلتا.",
        "climate_en": "Upper Egypt near Cairo; high heat and dust, less humidity than the Delta.",
        "stock_ar": "بيوت أسرية وعمارات متوسطة وإسكان جديد محدود.",
        "stock_en": "Family houses, mid-rise blocks, and limited new housing.",
        "places_ar": "حي شرق النيل، ناصر، الواسطى القريبة",
        "places_en": "East Nile district, Nasser, nearby Wasta",
        "access_ar": "الطريق الصحراوي الشرقي والزراعي الغربي.",
        "access_en": "Eastern desert road and western agricultural road.",
        "price_note_ar": "تكلفة عمالة بالجنيه أقل من القاهرة، مع بند نقل للخامات المتخصصة.",
        "price_note_en": "Lower EGP labor than Cairo, plus freight for specialist materials.",
    },
    "المنيا": {
        "en": "Minya",
        "slug": "minya",
        "gov_ar": "المنيا",
        "gov_en": "Minya",
        "tier": "upper",
        "climate_ar": "حرارة صعيد مرتفعة؛ العزل الحراري للأسطح أهم من العزل الساحلي.",
        "climate_en": "High Upper-Egypt heat; roof thermal insulation matters more than coastal insulation.",
        "stock_ar": "بيوت على النيل وعمارات بالمدينة الجديدة وأحياء قديمة ضيقة.",
        "stock_en": "Nile houses, New Minya blocks, and tight older alleys.",
        "places_ar": "المنيا الجديدة، وسط البلد، كورنيش النيل",
        "places_en": "New Minya, downtown, Nile corniche",
        "access_ar": "الطريق الصحراوي؛ جدولة التوريد من القاهرة أسبوعية غالبًا.",
        "access_en": "Desert road; Cairo freight is often weekly.",
        "price_note_ar": "ميزانيات بالجنيه تميل للتشطيب العملي والمتانة الحرارية.",
        "price_note_en": "EGP budgets favor practical finishes and heat durability.",
    },
    "أسيوط": {
        "en": "Assiut",
        "slug": "assiut",
        "gov_ar": "أسيوط",
        "gov_en": "Assiut",
        "tier": "upper",
        "climate_ar": "من أحر مدن مصر صيفًا؛ التكييف والعزل الحراري ليسا كماليات.",
        "climate_en": "Among Egypt’s hottest summers; AC and thermal insulation are not optional.",
        "stock_ar": "عمارات جامعية وبيوت قديمة وأسيوط الجديدة.",
        "stock_en": "University blocks, older houses, and New Assiut.",
        "places_ar": "أسيوط الجديدة، حي الوليدية، الحمراء",
        "places_en": "New Assiut, Walidia, Hamra",
        "access_ar": "الطريق الصحراوي الغربي؛ التوريد يحتاج تجميع طلبات.",
        "access_en": "Western desert road; deliveries work best as batched orders.",
        "price_note_ar": "أسعار بالجنيه تراعي الحرارة في اختيار الخامات لا الماركات الفاخرة فقط.",
        "price_note_en": "EGP pricing follows heat-ready materials, not only luxury brands.",
    },
    "سوهاج": {
        "en": "Sohag",
        "slug": "sohag",
        "gov_ar": "سوهاج",
        "gov_en": "Sohag",
        "tier": "upper",
        "climate_ar": "حرارة جافة؛ الدهانات الرخيصة تتكلّس وتتفتت خلال موسم واحد.",
        "climate_en": "Dry heat; cheap paints chalk and flake within one season.",
        "stock_ar": "بيوت أسرية وعمارات بالمدينة الجديدة.",
        "stock_en": "Family houses and New Sohag blocks.",
        "places_ar": "سوهاج الجديدة، الكوثر، حي البر الشرقي",
        "places_en": "New Sohag, Kawthar, East Bank",
        "access_ar": "صحراوي الغربي؛ زمن التوريد أطول.",
        "access_en": "Western desert road; longer lead times.",
        "price_note_ar": "التسعير بالجنيه يفضّل خامات حرارية متوسطة على التشطيب الموسمي.",
        "price_note_en": "EGP quotes prefer mid thermal materials over seasonal finishes.",
    },
    "قنا": {
        "en": "Qena",
        "slug": "qena",
        "gov_ar": "قنا",
        "gov_en": "Qena",
        "tier": "upper",
        "climate_ar": "حرارة شديدة وسطوع شمس؛ الواجهات الداكنة ترفع حرارة الداخل.",
        "climate_en": "Intense heat and sun; dark facades overheat interiors.",
        "stock_ar": "مساكن تقليدية وامتدادات جديدة محدودة.",
        "stock_en": "Traditional homes and limited new extensions.",
        "places_ar": "قنا الجديدة، دشنا القريبة، وسط قنا",
        "places_en": "New Qena, nearby Dishna, downtown Qena",
        "access_ar": "طريق الصعيد؛ التنسيق المسبق للخامات ضروري.",
        "access_en": "Upper Egypt road; materials must be planned ahead.",
        "price_note_ar": "بند النقل بالجنيه ظاهر في أي تشطيب غير محلي.",
        "price_note_en": "Freight is a visible EGP cost for non-local finishes.",
    },
    "الأقصر": {
        "en": "Luxor",
        "slug": "luxor",
        "gov_ar": "الأقصر",
        "gov_en": "Luxor",
        "tier": "upper",
        "climate_ar": "حرارة سياحية وغبار ناعم؛ البيوت والإيجارات السياحية تحتاج صيانة دورية.",
        "climate_en": "Tourist-season heat and fine dust; homes and holiday rentals need regular upkeep.",
        "stock_ar": "بيوت أثرية المحيط وعمارات حديثة بالكرنك والطود.",
        "stock_en": "Houses near heritage zones and newer Karnak and Tawd blocks.",
        "places_ar": "الكرنك، الطود، البر الغربي",
        "places_en": "Karnak, Tawd, West Bank",
        "access_ar": "قيود قرب المناطق الأثرية على الضوضاء والهدم.",
        "access_en": "Heritage-adjacent limits on noise and demolition.",
        "price_note_ar": "أعمال الفنادق الصغيرة والإيجارات السياحية تسعَّر بالجنيه حسب الموسم.",
        "price_note_en": "Small hotels and holiday lets are priced in EGP by season.",
    },
    "أسوان": {
        "en": "Aswan",
        "slug": "aswan",
        "gov_ar": "أسوان",
        "gov_en": "Aswan",
        "tier": "upper",
        "climate_ar": "جاف وشديد الحرارة؛ أي خشب غير متأقلم يتشقق.",
        "climate_en": "Very hot and dry; unacclimatized wood splits.",
        "stock_ar": "بيوت نوبية حديثة وعمارات بالمدينة وأعمال نيلية.",
        "stock_en": "Contemporary Nubian houses, city blocks, and Nile-side work.",
        "places_ar": "السيل، حى كيما، جزيرة أسوان",
        "places_en": "El Sail, Kima, Aswan island",
        "access_ar": "أبعد نقطة توريد معتادة؛ نجمع الطلبات لتقليل النقل.",
        "access_en": "The farthest regular freight point; we batch orders to cut haulage.",
        "price_note_ar": "النقل بالجنيه جزء أساسي من المقايسة لا بندًا هامشيًا.",
        "price_note_en": "EGP freight is a core quote line, not a footnote.",
    },
    "الرحاب": {
        "en": "Al Rehab",
        "slug": "rehab",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "premium",
        "climate_ar": "كمبوند مفتوح شرق القاهرة؛ الغبار والحرارة كالتجمع مع لوائح ألوان صارمة.",
        "climate_en": "Open East-Cairo compound; dust and heat like Fifth Settlement plus strict color rules.",
        "stock_ar": "فيلات وعمارات بأحياء مرقمة ولوائح مطور واضحة للواجهات.",
        "stock_en": "Numbered-phase villas and blocks with clear developer facade rules.",
        "places_ar": "الرحاب 1 إلى 6، السوق، الجولف",
        "places_en": "Rehab 1–6, the souq, the golf area",
        "access_ar": "بوابات الرحاب ومواعيد توريد محددة.",
        "access_en": "Rehab gates and fixed delivery slots.",
        "price_note_ar": "التشطيب بالجنيه محكوم بدليل المرحلة واللون المعتمد.",
        "price_note_en": "EGP finishing follows the phase handbook and approved colors.",
    },
    "مستقبل سيتي": {
        "en": "Mostakbal City",
        "slug": "mostakbal-city",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "premium",
        "climate_ar": "مدينة جديدة على طريق السويس؛ حرارة وغبار مع وحدات حديثة التسليم.",
        "climate_en": "New city on Suez Road; heat, dust, and freshly handed-over units.",
        "stock_ar": "كمبوندات مطورين كبار بمراحل تسليم متتالية.",
        "stock_en": "Major-developer compounds in rolling handover phases.",
        "places_ar": "كمبوندات المستقبل، مراحل التسليم الأولى",
        "places_en": "Mostakbal compounds and first handover phases",
        "access_ar": "طريق السويس وبوابات المطور.",
        "access_en": "Suez Road and developer gates.",
        "price_note_ar": "تسعير بالجنيه قريب من مدينتي والتجمع للوحدات الجديدة.",
        "price_note_en": "EGP pricing close to Madinaty and Fifth Settlement for new units.",
    },
    "الشروق": {
        "en": "Shorouk",
        "slug": "shorouk",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "mid",
        "climate_ar": "القاهرة الجديدة الغربية-الشرقية؛ غبار وحركة على طريق الإسماعيلية.",
        "climate_en": "New Cairo belt; dust and Ismailia-road traffic.",
        "stock_ar": "عمارات وكمبوندات متوسطة وكثافة أعلى من التجمع في بعض الأحياء.",
        "stock_en": "Mid compounds and blocks, denser than Fifth Settlement in some pockets.",
        "places_ar": "الحي الأول حتى الثامن، الشروق الجديدة",
        "places_en": "Districts 1–8 and New Shorouk",
        "access_ar": "طريق الإسماعيلية الصحراوي.",
        "access_en": "Ismailia desert road.",
        "price_note_ar": "شريحة بالجنيه بين مدينة نصر والتجمع.",
        "price_note_en": "EGP band between Nasr City and Fifth Settlement.",
    },
    "المعادي": {
        "en": "Maadi",
        "slug": "maadi",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "heritage",
        "climate_ar": "أشجار ورطوبة نيلية أخف من الزمالك؛ فيلات قديمة وأخشاب تحتاج صيانة.",
        "climate_en": "Trees and milder Nile humidity than Zamalek; old villas and wood need upkeep.",
        "stock_ar": "فيلات تراثية وعمارات هادئة ومناطق Digla وNew Maadi.",
        "stock_en": "Heritage villas, quiet blocks, Digla and New Maadi.",
        "places_ar": "المعادي القديمة، دجلة، المعادي الجديدة، ثكنات المعادي",
        "places_en": "Old Maadi, Degla, New Maadi, Sarayat",
        "access_ar": "شارع 9 والكورنيش؛ قيود على الهدم في الفيلات.",
        "access_en": "Road 9 and the corniche; villa demolition is restricted.",
        "price_note_ar": "ترميم الفيلات بالجنيه أعلى من إعادة دهان شقة حديثة.",
        "price_note_en": "Villa restoration costs more in EGP than repainting a modern flat.",
    },
    "مصر الجديدة": {
        "en": "Heliopolis",
        "slug": "heliopolis",
        "gov_ar": "القاهرة",
        "gov_en": "Cairo",
        "tier": "heritage",
        "climate_ar": "كثافة حضرية وتراث معماري؛ الواجهات والجص يحتاجان ترميمًا متخصصًا.",
        "climate_en": "Urban density and heritage fabric; facades and plaster need specialist restoration.",
        "stock_ar": "عماراتbaron وكورنيش وأحياء مثل الميرغني والكوربة والنزهة.",
        "stock_en": "Historic blocks plus Merghani, Korba and Nozha.",
        "places_ar": "الكوربة، الميرغني، النزهة، ألماظة",
        "places_en": "Korba, Merghani, Nozha, Almaza",
        "access_ar": "صلاح سالم وطريق المطار؛ تصاريح في بعض الشوارع التراثية.",
        "access_en": "Salah Salem and airport road; permits on some heritage streets.",
        "price_note_ar": "أعمال الترميم بالجنيه أعلى من التشطيب الحديث في التجمع.",
        "price_note_en": "Restoration EGP rates exceed modern finishing in Fifth Settlement.",
    },
    "الساحل الشمالي": {
        "en": "North Coast",
        "slug": "north-coast",
        "gov_ar": "مطروح والبحيرة",
        "gov_en": "Matrouh and Beheira",
        "tier": "coastal",
        "climate_ar": "ملوحة ورطوبة ورياح موسمية؛ كل معدن وخشب ودهان يجب أن يكون ساحلي المواصفات.",
        "climate_en": "Salt, humidity and seasonal wind; metal, wood and paint must be marine-spec.",
        "stock_ar": "شاليهات وفلل موسمية في هاسيندا ومارينا وسي سايد وأمواج.",
        "stock_en": "Seasonal chalets and villas in Hacienda, Marina, Sea View and Amwaj.",
        "places_ar": "مارينا، هاسيندا، أمواج، سي شور، رأس الحكمة القريبة",
        "places_en": "Marina, Hacienda, Amwaj, Sea Shore, nearby Ras El Hekma",
        "access_ar": "الطريق الدولي الساحلي؛ العمل المكثف قبل الموسم (مارس–مايو) أفضل.",
        "access_en": "Coastal international road; heavy work is best before season (March–May).",
        "price_note_ar": "الموسمية ترفع أجرة الفرق بالجنيه صيفًا، والخامات الساحلية أغلى.",
        "price_note_en": "Seasonality lifts EGP crew rates in summer; marine materials cost more.",
    },
    "رأس الحكمة": {
        "en": "Ras El Hekma",
        "slug": "ras-el-hekma",
        "gov_ar": "مطروح",
        "gov_en": "Matrouh",
        "tier": "coastal",
        "climate_ar": "رأس على المتوسط برياح وملوحة عالية؛ الشاليهات الجديدة تحتاج خامات بحرية من اليوم الأول.",
        "climate_en": "A Mediterranean headland with strong wind and salt; new chalets need marine-spec materials from day one.",
        "stock_ar": "مشروعات سياحية وفيلات ساحلية حديثة التسليم على مراحل.",
        "stock_en": "Tourism projects and coastal villas handed over in phases.",
        "places_ar": "المشروعات الساحلية، التوسعات الغربية لرأس الحكمة",
        "places_en": "Coastal developments and western Ras El Hekma expansions",
        "access_ar": "الطريق الدولي الساحلي؛ العمل الكثيف أفضل قبل موسم الصيف.",
        "access_en": "Coastal international road; heavy work is best before summer season.",
        "price_note_ar": "خامات مقاومة للملوحة وأجرة الموسم ترفع التكلفة بالجنيه عن مدن الدلتا.",
        "price_note_en": "Salt-proof materials and seasonal crews raise EGP cost above Delta cities.",
    },
    "الغردقة والبحر الأحمر": {
        "en": "Hurghada and the Red Sea",
        "slug": "hurghada-red-sea",
        "gov_ar": "البحر الأحمر",
        "gov_en": "Red Sea",
        "tier": "coastal",
        "climate_ar": "حرارة جافة وملوحة البحر الأحمر؛ التكييف والعزل الحراري أولوية مع حماية المعادن.",
        "climate_en": "Dry heat and Red Sea salt; AC, thermal insulation, and metal protection come first.",
        "stock_ar": "منتجعات وشقق سياحية وفيلات في الغردقة والجونة وسهل حشيش.",
        "stock_en": "Resorts, holiday apartments and villas in Hurghada, El Gouna and Sahl Hasheesh.",
        "places_ar": "الغردقة، الجونة، سهل حشيش، مكادي",
        "places_en": "Hurghada, El Gouna, Sahl Hasheesh, Makadi",
        "access_ar": "طريق الكورنيش والمطار؛ مواسم السياحة تزحم التوريد.",
        "access_en": "Corniche and airport roads; tourist peaks crowd deliveries.",
        "price_note_ar": "أعمال الإيجار السياحي تُسعَّر بالجنيه حسب الموسم ونوع الوحدة.",
        "price_note_en": "Holiday-rental jobs are priced in EGP by season and unit type.",
    },
    "العين السخنة": {
        "en": "Ain Sokhna",
        "slug": "ain-sokhna",
        "gov_ar": "السويس",
        "gov_en": "Suez",
        "tier": "coastal",
        "climate_ar": "خليج السويس حار وملحي؛ الواجهات والخزانات تتأثر بالملح أسرع من القاهرة.",
        "climate_en": "Hot, salty Suez Gulf air; facades and tanks corrode faster than in Cairo.",
        "stock_ar": "قري سياحية وشاليهات وفيلات نهاية أسبوع على الطريق إلى الزعفرانة.",
        "stock_en": "Weekend chalets, villas and holiday villages toward Zafarana.",
        "places_ar": "بورتو السخنة، لا فيستا، تلال، العين السخنة المدينة",
        "places_en": "Porto Sokhna, La Vista, Telal, Ain Sokhna town",
        "access_ar": "طريق السويس العين السخنة؛ الزحام الخميس والجمعة يؤخر التوريد.",
        "access_en": "Suez–Ain Sokhna road; Thursday–Friday traffic delays deliveries.",
        "price_note_ar": "التشطيب الموسمي بالجنيه أعلى في الربيع قبل الإجازات.",
        "price_note_en": "Seasonal EGP finishing rates rise in spring before holidays.",
    },
    "العلمين الجديدة": {
        "en": "New Alamein",
        "slug": "new-alamein",
        "gov_ar": "مطروح",
        "gov_en": "Matrouh",
        "tier": "coastal",
        "climate_ar": "مدينة متوسطية جديدة؛ أبراج زجاجية تحتاج عزلًا حراريًا وملحيًا معًا.",
        "climate_en": "New Mediterranean city; glass towers need both thermal and salt insulation.",
        "stock_ar": "أبراج الساحل وأحياء سكنية حديثة التسليم.",
        "stock_en": "Coastal towers and newly handed-over districts.",
        "places_ar": "الأبراج الساحلية، الحي السكني، الداون تاون",
        "places_en": "Coastal towers, residential district, downtown",
        "access_ar": "الطريق الساحلي ووصلة العلمين؛ التصاريح في الأبراج إلزامية.",
        "access_en": "Coastal road and Alamein link; tower permits are mandatory.",
        "price_note_ar": "مواصفات الأبراج ترفع متوسط التكلفة بالجنيه عن شاليهات الساحل التقليدية.",
        "price_note_en": "Tower specs raise EGP averages above classic North Coast chalets.",
    },
}

SERVICE_EN = {
    "تشطيب شقق": "Apartment finishing",
    "تشطيب فلل": "Villa finishing",
    "ديكورات وتصميم داخلي": "Interior design and décor",
    "تشطيب شاليهات": "Chalet finishing",
    "تشطيب فلل ساحلية": "Coastal villa finishing",
    "نجار": "Carpenter",
    "سباك": "Plumber",
    "كهربائي": "Electrician",
    "فني تكييف": "AC technician",
    "نقاش": "Painter",
    "مبلط": "Tiler",
    "حداد": "Welder / metal worker",
    "فني ألوميتال": "Aluminium technician",
    "فني رخام": "Marble technician",
    "صيانة منازل وفلل": "Home and villa maintenance",
    "عزل أسطح": "Roof insulation",
    "كشف تسربات": "Leak detection",
    "تنظيف": "Cleaning",
    "تنظيف منازل وفلل": "Home and villa cleaning",
    "مكافحة حشرات": "Pest control",
    "مكافحة الحشرات": "Pest control",
    "تفصيل مطابخ": "Custom kitchens",
    "جبساتي": "Gypsum technician",
    "دريسينج روم": "Dressing room",
    "ديكورات وتصميم داخلي ساحلي": "Coastal interior design",
    "فرش وتجهيز شاليهات للإيجار": "Chalet furnishing for rental",
    "كشف تسربات وعزل": "Leak detection and insulation",
}

CAT_EN = {
    "خدمات التشطيبات والديكور": "Finishing and décor",
    "خدمات التشطيبات والديكور الساحلية": "Coastal finishing and décor",
    "خدمات الحرفيين والفنيين": "Trades and technicians",
    "خدمات الصيانة": "Maintenance",
    "خدمات التنظيف": "Cleaning",
    "خدمات كشف التسربات والعزل": "Leak detection and insulation",
    "خدمات مكافحة الحشرات والتعقيم": "Pest control and sanitizing",
}

CAT_SLUG = {
    "خدمات التشطيبات والديكور": "finishing-decor",
    "خدمات التشطيبات والديكور الساحلية": "coastal-finishing",
    "خدمات الحرفيين والفنيين": "craftsmen",
    "خدمات الصيانة": "maintenance",
    "خدمات التنظيف": "cleaning",
    "خدمات كشف التسربات والعزل": "leaks-insulation",
    "خدمات مكافحة الحشرات والتعقيم": "pest-control",
}


def city_info(name: str) -> dict:
    if name in CITIES:
        return CITIES[name]
    # fallback so unknown labels still get Egypt-specific copy
    return {
        "en": name,
        "slug": "egypt",
        "gov_ar": "مصر",
        "gov_en": "Egypt",
        "tier": "mid",
        "climate_ar": "مناخ مصري متنوع بين الحر الصحراوي ورطوبة الدلتا والسواحل.",
        "climate_en": "Egyptian climate ranging from desert heat to Delta and coastal humidity.",
        "stock_ar": "وحدات سكنية مصرية تحتاج تشطيبًا أو صيانة بالجنيه المصري.",
        "stock_en": "Egyptian homes that need finishing or maintenance priced in EGP.",
        "places_ar": "الأحياء السكنية المحيطة",
        "places_en": "Surrounding residential districts",
        "access_ar": "ننظّم الزيارة حسب المحافظة وسهولة التوريد.",
        "access_en": "We schedule visits by governorate and delivery access.",
        "price_note_ar": "التسعير بالجنيه المصري بعد المعاينة.",
        "price_note_en": "Pricing is in EGP after inspection.",
    }


def service_key(title: str, city: str) -> str:
    t = title.replace(f" في {city}", "").replace(f" {city}", "").strip()
    return t
